[package]
name = "rust-lbm"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.100"
macroquad = "0.4"
ndarray = "0.16.1"
colorous = "1.0.12"
